// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T5_PR1.Data;

#nullable disable

namespace T5_PR1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250326155217_CanviPropietats")]
    partial class CanviPropietats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("T5_PR1.Models.ConsumAigua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Any")
                        .HasColumnType("int");

                    b.Property<string>("Comarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConsumDomesticPerCapita")
                        .HasColumnType("float");

                    b.Property<string>("Poblacio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsumsAigua");
                });

            modelBuilder.Entity("T5_PR1.Models.IndicadorEnergetic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CCAC_GasolinaAuto")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_DemandaElectr")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_ProdDisp")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_ProdNeta")
                        .HasColumnType("float");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("IndicadorsEnergetics");
                });

            modelBuilder.Entity("T5_PR1.Models.Simulacio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Benefici")
                        .HasColumnType("float");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<double>("Dada")
                        .HasColumnType("float");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("EnergiaGenerada")
                        .HasColumnType("float");

                    b.Property<double>("Preu")
                        .HasColumnType("float");

                    b.Property<double>("Rati")
                        .HasColumnType("float");

                    b.Property<int?>("Tipus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Simulacions");
                });
#pragma warning restore 612, 618
        }
    }
}
